
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install dependencies
    init: npm install -g @angular/cli # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3001
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - Angular.ng-template.io/docs/introduction/getting-started/quickstart
    - Mikael.Angular-BeastCode
