
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install dependencies
    init: |
      npm install -g @angular/cli
      sync-done dependencies
  - name: Run local web server
    command: |
      sync-await dependencies
      await-port 3001
      cd holy-grail/ && ng serve --open --port 3001

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3001 for the frontend
    port: 3001
    onOpen: open-browser

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart